server:
  port: 9015
  

spring:
  application:
    name: API-GATEWAY
    
  config:
    import: optional:configserver:http://localhost:9016
  cloud:
    gateway:
      routes:
      - id : USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        filters:
        - name: CircuitBreaker
          args:
            name: USER-SERVICE
            fallbackuri: forward:/userservicefallback
        
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**
        filters:
        - name: CircuitBreaker
          args:
            name: RATING-SERVICE
            fallbackuri: forward:/ratingservicefallback
        
      - id: LAPTOP-SERVICE
        uri: lb://LAPTOP-SERVICE
        predicates:
        - Path=/laptops/**
        filters:
        - name: CircuitBreaker
          args:
            name: LAPTOP-SERVICE
            fallbackuri: forward:/laptopservicefallback
      - id: USEDLAPTOP-SERVICE
        uri: lb://USEDLAPTOP-SERVICE
        predicates:
        - Path=/usedlaptops/**
        filters:
        - name: CircuitBreaker
          args:
            name: USEDLAPTOP-SERVICE
            fallbackuri: forward:/usedlaptopservicefallback
            
hystrix:
  command:
    falbackcmd:
       execution:
         isolation:
           thread:
             timeoutInMilliseconds: 4000
             
                  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info, metrics
        

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
   

    