server:
  port: 9016
      
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/saurabhpachbhai/config-server-laptopfinder
